import Head from 'next/head';

import Router, { useRouter } from 'next/router';




export default function Home() {
  const router = useRouter();
  return (
    <div className='h-full bg-zinc-600'>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className='flex items-center justify-center h-screen'>
        <div className='flex items-center justify-center h-4/5 w-4/5 border-gray-300 shadow-2xl shadow-orange-300 '>
          <div className='flex flex-col items-center text-center relative -top-56 '>
            <h1 className='text-white font-semibold text-5xl'>Salve, mi chiamo Francesco</h1>
            <p className='items-center text-white font-semibold text-4xl relative top-52'>E questo è il mio portfolio personale...
            </p>

          </div>
          <span onClick={() => router.push('/about')} className='flex items-center text-center justify-center h-4/5 w-72  absolute left-3/4 cursor-pointer transition-all ease-in-out duration-100 hover:bg-zinc-700 '>
            <svg onClick={() => router.push('/about')} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-16 h-16 absolute left-28 text-orange-300 transition-all ease-in-out duration-100 hover:scale-125 hover:text-orange-500">
              <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
            </svg>
          </span>
        </div>
      </div>





    </div>
  )
}
